name: Build_and _test

on:
  push


jobs:
  
  build_and_test:

    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v2
      - run: g++ -Wall *.cpp
      - run: ./harc.sh 
      - run: diff kimenetek.txt jo_kimenetek.txt
      
